Repository One-Trillion-Club/HUMATE-Android, pull requests merged in 2024-08, with the labels that each got.

#11 [MEMBER] 회원가입 액티비티 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/otclub/humate/LogInActivity.kt
  app/src/main/res/drawable/light_gray_border.xml
  app/src/main/res/drawable/main_large_button.xml
  app/src/main/res/layout/activity_log_in.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values/colors.xml
Labels: ✨ feat

#17 [CHAT] 서버와 WebSocket 연결
  app/build.gradle
  app/src/main/java/com/otclub/humate/chat/ChatFragment.kt
  app/src/main/java/com/otclub/humate/chat/ChatWebSocketClient.kt
  app/src/main/res/layout/fragment_chat.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: ✨ feat

#21 [CHAT] OkHttp로 웹소켓 통신, 재연결 구현
  app/src/main/java/com/otclub/humate/chat/ChatFragment.kt
  app/src/main/java/com/otclub/humate/chat/ChatWebSocketClient.kt
  app/src/main/java/com/otclub/humate/chat/ChatWebSocketListener.kt
  app/src/main/res/values/colors.xml
Labels: ✨ feat

#22 [ACTIVITY] 완료된 활동 목록 및 새로운 활동 목록 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/otclub/humate/MissionFragment.kt
  app/src/main/java/com/otclub/humate/mission/adapter/ClearedMissionAdapter.kt
  app/src/main/java/com/otclub/humate/mission/adapter/NewMissionAdapter.kt
  app/src/main/java/com/otclub/humate/mission/api/MissionService.kt
  app/src/main/java/com/otclub/humate/mission/data/ClearedMissionDTO.kt
  app/src/main/java/com/otclub/humate/mission/data/MissionResponseDTO.kt
  app/src/main/java/com/otclub/humate/mission/data/NewMission.kt
  app/src/main/java/com/otclub/humate/mission/fragment/ClearedMissionFragment.kt
  app/src/main/java/com/otclub/humate/mission/fragment/NewMissionFragment.kt
  app/src/main/java/com/otclub/humate/mission/viewModel/MissionViewModel.kt
  app/src/main/res/drawable/ic_mypage_selected.xml
  app/src/main/res/drawable/mission_button_border.xml
  app/src/main/res/drawable/mission_image_border.xml
  app/src/main/res/drawable/mission_purple_background.xml
  app/src/main/res/layout/fragment_cleared_mission.xml
  app/src/main/res/layout/fragment_mission.xml
  app/src/main/res/layout/fragment_new_mission.xml
  app/src/main/res/layout/item_cleared_mission.xml
  app/src/main/res/layout/item_new_mission.xml
  app/src/main/res/navigation/nav_graph.xml
  build.gradle
Labels: ✨ feat

#24 [ACTIVITY] 새로운 활동 상세 페이지 구현
  app/src/main/java/com/otclub/humate/mission/adapter/NewMissionAdapter.kt
  app/src/main/java/com/otclub/humate/mission/api/MissionService.kt
  app/src/main/java/com/otclub/humate/mission/data/NewMissionDetailsDTO.kt
  app/src/main/java/com/otclub/humate/mission/fragment/NewMissionDetailsFragment.kt
  app/src/main/java/com/otclub/humate/mission/fragment/NewMissionFragment.kt
  app/src/main/java/com/otclub/humate/mission/viewModel/NewMissionDetailsViewModel.kt
  app/src/main/res/layout/fragment_new_mission_details.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: ✨ feat

#27 [CHAT] 채팅 데이터 전송 및 통신 메서드 구현
  app/src/main/java/com/otclub/humate/chat/ChatFragment.kt
  app/src/main/java/com/otclub/humate/chat/ChatWebSocketListener.kt
  app/src/main/java/com/otclub/humate/chat/data/ChatMessageRequestDTO.kt
  app/src/main/java/com/otclub/humate/chat/data/ChatMessageResponseDTO.kt
  app/src/main/java/com/otclub/humate/chat/data/MessageType.kt
Labels: ✨ feat

#29 [ACTIVITY] 완료된 활동 상세 조회 구현
  app/src/main/java/com/otclub/humate/mission/adapter/ClearedMissionAdapter.kt
  app/src/main/java/com/otclub/humate/mission/adapter/ImagePagerAdapter.kt
  app/src/main/java/com/otclub/humate/mission/api/MissionService.kt
  app/src/main/java/com/otclub/humate/mission/data/ClearedMissionDetailsDTO.kt
  app/src/main/java/com/otclub/humate/mission/fragment/ClearedMissionDetailsFragment.kt
  app/src/main/java/com/otclub/humate/mission/fragment/ClearedMissionFragment.kt
  app/src/main/java/com/otclub/humate/mission/fragment/NewMissionDetailsFragment.kt
  app/src/main/java/com/otclub/humate/mission/viewModel/ClearedMissionDetailsViewModel.kt
  app/src/main/res/layout/fragment_cleared_mission_details.xml
  app/src/main/res/layout/mission_image_pager.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: ✨ feat

#33 [MEMBER] 한국인 회원가입 프라그먼트 구현
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/otclub/humate/MainActivity.kt
  app/src/main/java/com/otclub/humate/auth/activity/AuthActivity.kt
  app/src/main/java/com/otclub/humate/auth/activity/LogInActivity.kt
  app/src/main/java/com/otclub/humate/auth/fragment/InputIdPasswordFragment.kt
  app/src/main/java/com/otclub/humate/auth/fragment/InputProfileFragment.kt
  app/src/main/java/com/otclub/humate/auth/fragment/InputUserInfoFragment.kt
  app/src/main/java/com/otclub/humate/auth/fragment/SelectSignUpTypeFragment.kt
  app/src/main/java/com/otclub/humate/auth/fragment/SignInFragment.kt
  app/src/main/java/com/otclub/humate/auth/fragment/VerifyPhoneFragment.kt
  app/src/main/res/drawable/auth_light_gray_border.xml
  app/src/main/res/drawable/auth_main_large_button.xml
  app/src/main/res/drawable/ic_member_profile_default.xml
  app/src/main/res/drawable/ic_member_upload_image.xml
  app/src/main/res/drawable/member_light_green_background.xml
  app/src/main/res/drawable/member_light_purple_background.xml
  app/src/main/res/layout/activity_auth.xml
  app/src/main/res/layout/auth_fragment_input_profile.xml
  app/src/main/res/layout/auth_fragment_input_user_info.xml
  app/src/main/res/layout/auth_fragment_select_sign_up_type.xml
  app/src/main/res/layout/auth_fragment_sign_in.xml
  app/src/main/res/layout/auth_fragment_verify_phone.xml
  app/src/main/res/layout/fragment_input_id_password.xml
  app/src/main/res/layout/fragment_new_mission_details.xml
  app/src/main/res/values/colors.xml
Labels: ✨ feat

#32 [ACTIVITY] 동행 목록 조회 페이지 구현
  app/src/main/java/com/otclub/humate/mission/adapter/MatchingAdpater.kt
  app/src/main/java/com/otclub/humate/mission/api/MissionService.kt
  app/src/main/java/com/otclub/humate/mission/data/MatchingResponseDTO.kt
  app/src/main/java/com/otclub/humate/mission/fragment/MatchingFragment.kt
  app/src/main/java/com/otclub/humate/mission/viewModel/MatchingViewModel.kt
  app/src/main/res/drawable/mission_profile.xml
  app/src/main/res/layout/activity_matching_item.xml
  app/src/main/res/layout/fragment_matching.xml
  app/src/main/res/menu/bottom_nav.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: ✨ feat

#37 [ACTIVITY] 동행 목록에서 활동 목록으로 이동 기능 구현
  app/src/main/java/com/otclub/humate/mission/adapter/MatchingAdpater.kt
  app/src/main/java/com/otclub/humate/mission/api/MissionService.kt
  app/src/main/java/com/otclub/humate/mission/fragment/ClearedMissionFragment.kt
  app/src/main/java/com/otclub/humate/mission/fragment/MatchingFragment.kt
  app/src/main/java/com/otclub/humate/mission/fragment/NewMissionFragment.kt
  app/src/main/java/com/otclub/humate/mission/viewModel/MissionViewModel.kt
  app/src/main/res/layout/activity_matching_item.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: ✨ feat

#42 [ACTIVITY] 활동 업로드 구현 및 동행 목록, 활동 목록 개선
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/otclub/humate/mission/adapter/ClearedMissionAdapter.kt
  app/src/main/java/com/otclub/humate/mission/adapter/UploadMissionAdapter.kt
  app/src/main/java/com/otclub/humate/mission/api/MissionService.kt
  app/src/main/java/com/otclub/humate/mission/data/CommonResponseDTO.kt
  app/src/main/java/com/otclub/humate/mission/fragment/ClearedMissionDetailsFragment.kt
  app/src/main/java/com/otclub/humate/mission/fragment/ClearedMissionFragment.kt
  app/src/main/java/com/otclub/humate/mission/fragment/MatchingFragment.kt
  app/src/main/java/com/otclub/humate/mission/fragment/MissionUploadFragment.kt
  app/src/main/java/com/otclub/humate/mission/fragment/NewMissionDetailsFragment.kt
  app/src/main/java/com/otclub/humate/mission/fragment/NewMissionFragment.kt
  app/src/main/java/com/otclub/humate/mission/viewModel/ClearedMissionDetailsViewModel.kt
  app/src/main/java/com/otclub/humate/mission/viewModel/MatchingViewModel.kt
  app/src/main/java/com/otclub/humate/mission/viewModel/MissionViewModel.kt
  app/src/main/java/com/otclub/humate/mission/viewModel/NewMissionDetailsViewModel.kt
  app/src/main/res/drawable/img_box_duotone_line.xml
  app/src/main/res/layout/common_toolbar.xml
  app/src/main/res/layout/fragment_cleared_mission.xml
  app/src/main/res/layout/fragment_mission_upload.xml
  app/src/main/res/layout/item_cleared_mission.xml
  app/src/main/res/layout/item_mission_upload_image.xml
  app/src/main/res/layout/mate_fragment_post_list_filter.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: ✨ feat

#48 [MEMBER] 로그인, 로그아웃 상태 저장/확인
  app/src/main/java/com/otclub/humate/MainActivity.kt
  app/src/main/java/com/otclub/humate/MyPageFragment.kt
  app/src/main/java/com/otclub/humate/auth/api/AuthService.kt
  app/src/main/java/com/otclub/humate/auth/fragment/InputProfileFragment.kt
  app/src/main/java/com/otclub/humate/auth/fragment/SignInFragment.kt
  app/src/main/java/com/otclub/humate/auth/viewmodel/AuthViewModel.kt
  app/src/main/java/com/otclub/humate/member/api/MemberService.kt
  app/src/main/java/com/otclub/humate/member/fragment/MyPageFragment.kt
  app/src/main/java/com/otclub/humate/member/viewmodel/MemberViewModel.kt
  app/src/main/java/com/otclub/humate/sharedpreferences/SharedPreferencesManager.kt
  app/src/main/res/layout/member_fragment_my_page.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: ✨ feat

#52 [ACTIVITY] 동행 종료하기 기능 구현
  app/src/main/java/com/otclub/humate/MainActivity.kt
  app/src/main/java/com/otclub/humate/mission/api/MissionService.kt
  app/src/main/java/com/otclub/humate/mission/data/ClearedMissionDetailsDTO.kt
  app/src/main/java/com/otclub/humate/mission/data/MissionResponseDTO.kt
  app/src/main/java/com/otclub/humate/mission/fragment/ClearedMissionDetailsFragment.kt
  app/src/main/java/com/otclub/humate/mission/fragment/ClearedMissionFragment.kt
  app/src/main/java/com/otclub/humate/mission/fragment/MatchingFragment.kt
  app/src/main/java/com/otclub/humate/mission/fragment/NewMissionFragment.kt
  app/src/main/java/com/otclub/humate/mission/viewModel/MissionViewModel.kt
  app/src/main/res/layout/mission_toolbar.xml
  app/src/main/res/menu/mission_menu.xml
Labels: ✨ feat

#54 [REVIEW] 후기 등록 페이지 및 후기 제출 기능 구현
  app/src/main/java/com/otclub/humate/MainActivity.kt
  app/src/main/java/com/otclub/humate/mission/api/MissionService.kt
  app/src/main/java/com/otclub/humate/mission/data/ReviewRequestDTO.kt
  app/src/main/java/com/otclub/humate/mission/data/ReviewResponseDTO.kt
  app/src/main/java/com/otclub/humate/mission/fragment/ClearedMissionFragment.kt
  app/src/main/java/com/otclub/humate/mission/fragment/ReviewFragment.kt
  app/src/main/res/drawable/ic_bad_status.png
  app/src/main/res/drawable/ic_bad_status_selected.png
  app/src/main/res/drawable/ic_branch.png
  app/src/main/res/drawable/ic_date.png
  app/src/main/res/drawable/ic_excellent_status.png
  app/src/main/res/drawable/ic_excellent_status_selected.png
  app/src/main/res/drawable/ic_good_status.png
  app/src/main/res/drawable/ic_good_status_selected.png
  app/src/main/res/drawable/review_text_border.xml
  app/src/main/res/layout/fragment_review.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: ✨ feat

#56 [COMMON] 활동, 후기 도메인 전체적인 툴바 개선
  app/src/main/java/com/otclub/humate/MainActivity.kt
  app/src/main/java/com/otclub/humate/mate/fragment/PostListFragment.kt
  app/src/main/java/com/otclub/humate/mission/fragment/ClearedMissionDetailsFragment.kt
  app/src/main/java/com/otclub/humate/mission/fragment/ClearedMissionFragment.kt
  app/src/main/java/com/otclub/humate/mission/fragment/MatchingFragment.kt
  app/src/main/java/com/otclub/humate/mission/fragment/MissionUploadFragment.kt
  app/src/main/java/com/otclub/humate/mission/fragment/NewMissionDetailsFragment.kt
  app/src/main/java/com/otclub/humate/mission/fragment/NewMissionFragment.kt
  app/src/main/java/com/otclub/humate/mission/fragment/ReviewFragment.kt
  app/src/main/res/layout/fragment_cleared_mission.xml
  app/src/main/res/layout/fragment_cleared_mission_details.xml
  app/src/main/res/layout/fragment_matching.xml
  app/src/main/res/layout/fragment_mission_upload.xml
  app/src/main/res/layout/fragment_new_mission.xml
  app/src/main/res/layout/fragment_new_mission_details.xml
  app/src/main/res/layout/fragment_review.xml
Labels: ✨ feat

#60 [COMMON] request 시 쿠키 담아서 보내도록 설정
  app/build.gradle
  app/src/main/java/com/otclub/humate/retrofit/RetrofitConnection.kt
Labels: ✨ feat

#58 [CHAT] 채팅 내역 리스트 조회 구현
  app/src/main/java/com/otclub/humate/chat/adapter/ChatAdapter.kt
  app/src/main/java/com/otclub/humate/chat/adapter/ChatRoomAdapter.kt
  app/src/main/java/com/otclub/humate/chat/api/ChatRoomService.kt
  app/src/main/java/com/otclub/humate/chat/data/ChatRoomDetailDTO.kt
  app/src/main/java/com/otclub/humate/chat/fragment/ChatFragment.kt
  app/src/main/java/com/otclub/humate/chat/fragment/ChatRoomFragment.kt
  app/src/main/java/com/otclub/humate/chat/viewModel/ChatRoomViewModel.kt
  app/src/main/res/drawable/ic_chat_post_title.xml
  app/src/main/res/drawable/ic_chat_unread_badge.xml
  app/src/main/res/drawable/tab_basic_indicator.xml
  app/src/main/res/drawable/tab_indicator.xml
  app/src/main/res/layout/chat_room_fragment.xml
  app/src/main/res/layout/chat_room_item.xml
  app/src/main/res/menu/bottom_nav.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/colors.xml
Labels: ✨ feat

#61 [CHAT] 채팅방 UI 구현
  app/src/main/java/com/otclub/humate/MainActivity.kt
  app/src/main/java/com/otclub/humate/chat/fragment/ChatFragment.kt
  app/src/main/java/com/otclub/humate/chat/fragment/ChatRoomFragment.kt
  app/src/main/res/drawable/chat_input_box.xml
  app/src/main/res/drawable/chat_plus_button.xml
  app/src/main/res/drawable/chat_send_button.xml
  app/src/main/res/drawable/ic_logo_gray.xml
  app/src/main/res/drawable/ic_logo_purple.xml
  app/src/main/res/layout/chat_fragment.xml
  app/src/main/res/layout/chat_message_notice.xml
Labels: ✨ feat

#67 [CHAT] 채팅 과거 내역 조회 비동기 처리
  app/build.gradle
  app/src/main/java/com/otclub/humate/chat/adapter/ChatAdapter.kt
  app/src/main/java/com/otclub/humate/chat/api/ChatService.kt
  app/src/main/java/com/otclub/humate/chat/data/ChatMessageResponseDTO.kt
  app/src/main/java/com/otclub/humate/chat/fragment/ChatFragment.kt
  app/src/main/java/com/otclub/humate/chat/fragment/ChatRoomFragment.kt
  app/src/main/java/com/otclub/humate/chat/viewModel/ChatViewModel.kt
Labels: ✨ feat

#69 [ACTIVITY] 목록 이동 시 Button -> TabLayout으로 변경
  app/src/main/java/com/otclub/humate/mission/adapter/ClearedMissionAdapter.kt
  app/src/main/java/com/otclub/humate/mission/fragment/ClearedMissionFragment.kt
  app/src/main/java/com/otclub/humate/mission/fragment/NewMissionFragment.kt
  app/src/main/res/drawable/ic_mission_unselected.xml
  app/src/main/res/drawable/mission_completed.xml
  app/src/main/res/drawable/mission_pending.xml
  app/src/main/res/layout/fragment_cleared_mission.xml
  app/src/main/res/layout/fragment_new_mission.xml
  app/src/main/res/layout/fragment_new_mission_details.xml
  app/src/main/res/menu/bottom_nav.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feat

#71 [REVIEW] score Enum으로 관리
  app/src/main/java/com/otclub/humate/mission/data/ReviewRequestDTO.kt
  app/src/main/java/com/otclub/humate/mission/data/ReviewScore.kt
  app/src/main/java/com/otclub/humate/mission/fragment/ClearedMissionFragment.kt
  app/src/main/java/com/otclub/humate/mission/fragment/MissionUploadFragment.kt
  app/src/main/java/com/otclub/humate/mission/fragment/NewMissionFragment.kt
  app/src/main/java/com/otclub/humate/mission/fragment/ReviewFragment.kt
  app/src/main/java/com/otclub/humate/mission/viewModel/MissionViewModel.kt
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feat

#79 [ACTIVITY] 후기 스크롤뷰 적용 및 활동 목록 ... 적용
  app/src/main/res/layout/fragment_review.xml
  app/src/main/res/layout/item_cleared_mission.xml
  app/src/main/res/layout/item_new_mission.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feat

#82 [CHAT] 채팅리스트에서 채팅방 이동 통신
  app/src/main/java/com/otclub/humate/chat/adapter/ChatAdapter.kt
  app/src/main/java/com/otclub/humate/chat/data/ChatMessageRequestDTO.kt
  app/src/main/java/com/otclub/humate/chat/data/ChatMessageResponseDTO.kt
  app/src/main/java/com/otclub/humate/chat/data/MessageType.kt
  app/src/main/java/com/otclub/humate/chat/fragment/ChatFragment.kt
  app/src/main/java/com/otclub/humate/chat/fragment/ChatRoomFragment.kt
  app/src/main/res/drawable/chat_bubble_received.xml
  app/src/main/res/drawable/chat_bubble_sent.xml
  app/src/main/res/layout/chat_message_received.xml
  app/src/main/res/layout/chat_message_sent.xml
Labels: ✨ feat

#86 [MEMBER] 외국인 회원가입 구현
  app/src/main/java/com/otclub/humate/auth/data/VerifyPassportRequestDTO.kt
  app/src/main/java/com/otclub/humate/auth/fragment/ForeignerInputUserInfoFragment.kt
  app/src/main/java/com/otclub/humate/auth/fragment/InputIdPasswordFragment.kt
  app/src/main/java/com/otclub/humate/auth/fragment/SelectSignUpTypeFragment.kt
  app/src/main/java/com/otclub/humate/auth/fragment/VerifyPassportFragment.kt
  app/src/main/java/com/otclub/humate/auth/fragment/VerifyPhoneFragment.kt
  app/src/main/java/com/otclub/humate/auth/viewmodel/AuthViewModel.kt
  app/src/main/java/com/otclub/humate/sharedpreferences/SharedPreferencesManager.kt
  app/src/main/res/layout/auth_fragment_foreigner_input_user_info.xml
  app/src/main/res/layout/auth_fragment_verify_passport.xml
  app/src/main/res/layout/member_dialog_mate_detail.xml
  app/src/main/res/layout/member_item_mate.xml
  app/src/main/res/values/themes.xml
Labels: ✨ feat

#90 [ACTIVITY] 활동 관련 UI 및 기능 수정
  app/src/main/java/com/otclub/humate/mission/adapter/MatchingAdpater.kt
  app/src/main/java/com/otclub/humate/mission/adapter/UploadMissionAdapter.kt
  app/src/main/java/com/otclub/humate/mission/data/MatchingResponseDTO.kt
  app/src/main/java/com/otclub/humate/mission/fragment/ClearedMissionDetailsFragment.kt
  app/src/main/java/com/otclub/humate/mission/fragment/ClearedMissionFragment.kt
  app/src/main/java/com/otclub/humate/mission/fragment/MatchingFragment.kt
  app/src/main/java/com/otclub/humate/mission/fragment/MissionUploadFragment.kt
  app/src/main/java/com/otclub/humate/mission/fragment/NewMissionDetailsFragment.kt
  app/src/main/java/com/otclub/humate/mission/fragment/NewMissionFragment.kt
  app/src/main/java/com/otclub/humate/mission/fragment/ReviewFragment.kt
  app/src/main/res/drawable/ic_bad_status.png
  app/src/main/res/drawable/ic_bad_status.xml
  app/src/main/res/drawable/ic_bad_status_selected.png
  app/src/main/res/drawable/ic_bad_status_selected.xml
  app/src/main/res/drawable/ic_excellent_status.png
  app/src/main/res/drawable/ic_excellent_status.xml
  app/src/main/res/drawable/ic_excellent_status_selected.png
  app/src/main/res/drawable/ic_excellent_status_selected.xml
  app/src/main/res/drawable/ic_good_status.png
  app/src/main/res/drawable/ic_good_status.xml
  app/src/main/res/drawable/ic_good_status_selected.png
  app/src/main/res/drawable/ic_good_status_selected.xml
  app/src/main/res/drawable/matching_closed.xml
  app/src/main/res/drawable/matching_ongoing.xml
  app/src/main/res/layout/activity_matching_item.xml
  app/src/main/res/layout/fragment_cleared_mission.xml
  app/src/main/res/layout/fragment_cleared_mission_details.xml
  app/src/main/res/layout/fragment_mission_upload.xml
  app/src/main/res/layout/fragment_new_mission.xml
  app/src/main/res/layout/fragment_new_mission_details.xml
  app/src/main/res/layout/fragment_review.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values/colors.xml
Labels: ✨ feat

#91 [MEMBER] 영어 버전 및 NAV 수정
  app/src/main/java/com/otclub/humate/MainActivity.kt
  app/src/main/java/com/otclub/humate/auth/fragment/InputIdPasswordFragment.kt
  app/src/main/java/com/otclub/humate/auth/fragment/InputProfileFragment.kt
  app/src/main/java/com/otclub/humate/auth/fragment/SignInFragment.kt
  app/src/main/java/com/otclub/humate/auth/fragment/VerifyPassportFragment.kt
  app/src/main/java/com/otclub/humate/member/adapter/MateListAdapter.kt
  app/src/main/java/com/otclub/humate/member/fragment/MyMatesFragment.kt
  app/src/main/java/com/otclub/humate/member/fragment/MyPageFragment.kt
  app/src/main/java/com/otclub/humate/member/fragment/MyProfileFragment.kt
  app/src/main/res/layout/auth_fragment_input_profile.xml
  app/src/main/res/layout/auth_fragment_select_sign_up_type.xml
  app/src/main/res/layout/auth_fragment_sign_in.xml
  app/src/main/res/layout/common_toolbar.xml
  app/src/main/res/layout/fragment_input_id_password.xml
  app/src/main/res/layout/member_dialog_mate_detail.xml
  app/src/main/res/layout/member_fragment_my_page.xml
  app/src/main/res/layout/member_fragment_my_profile.xml
  app/src/main/res/layout/member_item_mate.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feat

#92 [CHAT] 채팅방 UI 수정
  app/src/main/java/com/otclub/humate/chat/adapter/ChatAdapter.kt
  app/src/main/java/com/otclub/humate/chat/adapter/ChatRoomAdapter.kt
  app/src/main/java/com/otclub/humate/chat/api/ChatService.kt
  app/src/main/java/com/otclub/humate/chat/fragment/ChatFragment.kt
  app/src/main/java/com/otclub/humate/chat/fragment/ChatRoomFragment.kt
  app/src/main/java/com/otclub/humate/chat/viewModel/ChatRoomViewModel.kt
  app/src/main/java/com/otclub/humate/chat/viewModel/ChatViewModel.kt
  app/src/main/java/com/otclub/humate/retrofit/RetrofitConnection.kt
  app/src/main/res/layout/chat_fragment.xml
  app/src/main/res/layout/chat_message_received.xml
  app/src/main/res/layout/chat_room_fragment.xml
  app/src/main/res/layout/chat_room_item.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feat

#94 [ACTIVITY] 미션 제목 내용 출력 시 한국인 외국인 언어에 맞게 출력하기
  app/src/main/java/com/otclub/humate/mission/adapter/ClearedMissionAdapter.kt
  app/src/main/java/com/otclub/humate/mission/adapter/NewMissionAdapter.kt
  app/src/main/java/com/otclub/humate/mission/data/ClearedMissionDTO.kt
  app/src/main/java/com/otclub/humate/mission/data/ClearedMissionDetailsDTO.kt
  app/src/main/java/com/otclub/humate/mission/data/NewMission.kt
  app/src/main/java/com/otclub/humate/mission/data/NewMissionDetailsDTO.kt
  app/src/main/java/com/otclub/humate/mission/fragment/ClearedMissionDetailsFragment.kt
  app/src/main/java/com/otclub/humate/mission/fragment/ClearedMissionFragment.kt
  app/src/main/java/com/otclub/humate/mission/fragment/MissionUploadFragment.kt
  app/src/main/java/com/otclub/humate/mission/fragment/NewMissionDetailsFragment.kt
  app/src/main/java/com/otclub/humate/mission/fragment/NewMissionFragment.kt
  app/src/main/java/com/otclub/humate/mission/viewModel/MissionViewModel.kt
  app/src/main/res/layout/fragment_cleared_mission_details.xml
  app/src/main/res/layout/fragment_review.xml
Labels: ✨ feat

#96 [COMMON] 로딩 창 구현
  app/src/main/java/com/otclub/humate/auth/fragment/InputProfileFragment.kt
  app/src/main/java/com/otclub/humate/auth/fragment/SignInFragment.kt
  app/src/main/java/com/otclub/humate/auth/fragment/VerifyPassportFragment.kt
  app/src/main/java/com/otclub/humate/auth/fragment/VerifyPhoneFragment.kt
  app/src/main/java/com/otclub/humate/chat/fragment/ChatFragment.kt
  app/src/main/java/com/otclub/humate/chat/fragment/ChatRoomFragment.kt
  app/src/main/java/com/otclub/humate/common/LoadingDialog.kt
  app/src/main/java/com/otclub/humate/member/fragment/MyProfileFragment.kt
  app/src/main/java/com/otclub/humate/mission/fragment/MissionUploadFragment.kt
  app/src/main/java/com/otclub/humate/retrofit/RetrofitConnection.kt
  app/src/main/res/layout/dialog_loading.xml
  app/src/main/res/layout/member_fragment_my_profile.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feat

#100 [REVIEW] Review 예외 처리
  app/src/main/java/com/otclub/humate/mission/adapter/ClearedMissionAdapter.kt
  app/src/main/java/com/otclub/humate/mission/fragment/ClearedMissionFragment.kt
  app/src/main/java/com/otclub/humate/mission/fragment/ReviewFragment.kt
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feat

#101 [CHAT] 메이트 채팅방 활성화 (맺기 버튼, 다이얼)
  app/src/main/java/com/otclub/humate/chat/adapter/ChatAdapter.kt
  app/src/main/java/com/otclub/humate/chat/adapter/ChatRoomAdapter.kt
  app/src/main/java/com/otclub/humate/chat/api/ChatRoomService.kt
  app/src/main/java/com/otclub/humate/chat/api/ChatService.kt
  app/src/main/java/com/otclub/humate/chat/data/ChatCreateCompanionRequestDTO.kt
  app/src/main/java/com/otclub/humate/chat/data/ChatRoomDetailDTO.kt
  app/src/main/java/com/otclub/humate/chat/data/MateUpdateRequestDTO.kt
  app/src/main/java/com/otclub/humate/chat/data/MessageType.kt
  app/src/main/java/com/otclub/humate/chat/fragment/ChatFragment.kt
  app/src/main/java/com/otclub/humate/chat/fragment/ChatRoomFragment.kt
  app/src/main/java/com/otclub/humate/chat/viewModel/ChatViewModel.kt
  app/src/main/res/drawable/chat_activity_arrows.xml
  app/src/main/res/drawable/chat_activity_notice.xml
  app/src/main/res/drawable/chat_dialog_button_background.xml
  app/src/main/res/drawable/chat_mate_button_default.xml
  app/src/main/res/drawable/chat_mate_button_pressed.xml
  app/src/main/res/layout/chat_activity_notice.xml
  app/src/main/res/layout/chat_dialog_confirmed.xml
  app/src/main/res/layout/chat_dialog_mate.xml
  app/src/main/res/layout/chat_dialog_mate_cancel.xml
  app/src/main/res/layout/chat_fragment.xml
  app/src/main/res/layout/chat_mate_button_default.xml
  app/src/main/res/layout/chat_mate_button_pressed.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feat

#103 [CHAT] ChatRoomDetailDTO에 memberId 추가하기
  app/src/main/java/com/otclub/humate/chat/data/ChatRoomDetailDTO.kt
  app/src/main/java/com/otclub/humate/chat/fragment/ChatFragment.kt
Labels: ✨ feat

#107 [CHAT] 채팅방 업데이트
  app/src/main/java/com/otclub/humate/chat/adapter/ChatAdapter.kt
  app/src/main/java/com/otclub/humate/chat/api/ChatService.kt
  app/src/main/java/com/otclub/humate/chat/data/ChatMessage.kt
  app/src/main/java/com/otclub/humate/chat/data/ChatMessageWebSocketResponseDTO.kt
  app/src/main/java/com/otclub/humate/chat/data/ChatSendMessageRequestDTO.kt
  app/src/main/java/com/otclub/humate/chat/fragment/ChatFragment.kt
  app/src/main/java/com/otclub/humate/chat/fragment/ChatWebSocketListener.kt
  app/src/main/java/com/otclub/humate/chat/viewModel/ChatViewModel.kt
  app/src/main/res/layout/chat_activity_notice.xml
  app/src/main/res/values/strings.xml
Labels: ✨ feat

#117 [MEMBER] 코드 주석 처리
  app/src/main/java/com/otclub/humate/auth/activity/AuthActivity.kt
  app/src/main/java/com/otclub/humate/auth/api/AuthService.kt
  app/src/main/java/com/otclub/humate/auth/data/CommonResponseDTO.kt
  app/src/main/java/com/otclub/humate/auth/data/GeneratePhoneCodeRequestDTO.kt
  app/src/main/java/com/otclub/humate/auth/data/LoginRequestDTO.kt
  app/src/main/java/com/otclub/humate/auth/data/SignUpRequestDTO.kt
  app/src/main/java/com/otclub/humate/auth/data/VerifyPassportRequestDTO.kt
  app/src/main/java/com/otclub/humate/auth/data/VerifyPhoneCodeRequestDTO.kt
  app/src/main/java/com/otclub/humate/auth/fragment/ForeignerInputUserInfoFragment.kt
  app/src/main/java/com/otclub/humate/auth/fragment/InputIdPasswordFragment.kt
  app/src/main/java/com/otclub/humate/auth/fragment/InputProfileFragment.kt
  app/src/main/java/com/otclub/humate/auth/fragment/InputUserInfoFragment.kt
  app/src/main/java/com/otclub/humate/auth/fragment/SelectSignUpTypeFragment.kt
  app/src/main/java/com/otclub/humate/auth/fragment/SignInFragment.kt
  app/src/main/java/com/otclub/humate/auth/fragment/VerifyPassportFragment.kt
  app/src/main/java/com/otclub/humate/auth/fragment/VerifyPhoneFragment.kt
  app/src/main/java/com/otclub/humate/auth/viewmodel/AuthViewModel.kt
  app/src/main/java/com/otclub/humate/chat/fragment/ChatFragment.kt
  app/src/main/java/com/otclub/humate/common/LoadingDialog.kt
  app/src/main/java/com/otclub/humate/member/adapter/MateListAdapter.kt
  app/src/main/java/com/otclub/humate/member/api/MemberService.kt
  app/src/main/java/com/otclub/humate/member/data/ModifyProfileRequestDTO.kt
  app/src/main/java/com/otclub/humate/member/data/ProfileResponseDTO.kt
  app/src/main/java/com/otclub/humate/member/fragment/MyMatesFragment.kt
  app/src/main/java/com/otclub/humate/member/fragment/MyPageFragment.kt
  app/src/main/java/com/otclub/humate/member/fragment/MyProfileFragment.kt
  app/src/main/java/com/otclub/humate/retrofit/RetrofitConnection.kt
  app/src/main/java/com/otclub/humate/sharedpreferences/SharedPreferencesManager.kt
  app/src/main/res/layout/auth_fragment_foreigner_input_user_info.xml
  app/src/main/res/layout/auth_fragment_input_id_password.xml
  app/src/main/res/layout/auth_fragment_input_profile.xml
  app/src/main/res/layout/auth_fragment_input_user_info.xml
  app/src/main/res/layout/auth_fragment_select_sign_up_type.xml
  app/src/main/res/layout/auth_fragment_sign_in.xml
  app/src/main/res/layout/auth_fragment_verify_passport.xml
  app/src/main/res/layout/auth_fragment_verify_phone.xml
  app/src/main/res/layout/dialog_loading.xml
  app/src/main/res/layout/member_dialog_mate_detail.xml
  app/src/main/res/layout/member_fragment_my_mates.xml
  app/src/main/res/layout/member_fragment_my_page.xml
  app/src/main/res/layout/member_fragment_my_profile.xml
  app/src/main/res/layout/member_item_mate.xml
Labels: documentation

#115 [ACTIVITY] 활동 관련 파일 주석 추가
  app/src/main/java/com/otclub/humate/mission/adapter/ClearedMissionAdapter.kt
  app/src/main/java/com/otclub/humate/mission/adapter/ImagePagerAdapter.kt
  app/src/main/java/com/otclub/humate/mission/adapter/MatchingAdpater.kt
  app/src/main/java/com/otclub/humate/mission/adapter/NewMissionAdapter.kt
  app/src/main/java/com/otclub/humate/mission/adapter/UploadMissionAdapter.kt
  app/src/main/java/com/otclub/humate/mission/api/MissionService.kt
  app/src/main/java/com/otclub/humate/mission/data/ClearedMissionDTO.kt
  app/src/main/java/com/otclub/humate/mission/data/ClearedMissionDetailsDTO.kt
  app/src/main/java/com/otclub/humate/mission/data/MatchingResponseDTO.kt
  app/src/main/java/com/otclub/humate/mission/data/MissionResponseDTO.kt
  app/src/main/java/com/otclub/humate/mission/data/NewMission.kt
  app/src/main/java/com/otclub/humate/mission/data/NewMissionDetailsDTO.kt
  app/src/main/java/com/otclub/humate/mission/data/ReviewRequestDTO.kt
  app/src/main/java/com/otclub/humate/mission/data/ReviewResponseDTO.kt
  app/src/main/java/com/otclub/humate/mission/data/ReviewScore.kt
  app/src/main/java/com/otclub/humate/mission/fragment/ClearedMissionDetailsFragment.kt
  app/src/main/java/com/otclub/humate/mission/fragment/ClearedMissionFragment.kt
  app/src/main/java/com/otclub/humate/mission/fragment/MatchingFragment.kt
  app/src/main/java/com/otclub/humate/mission/fragment/MissionUploadFragment.kt
  app/src/main/java/com/otclub/humate/mission/fragment/NewMissionDetailsFragment.kt
  app/src/main/java/com/otclub/humate/mission/fragment/NewMissionFragment.kt
  app/src/main/java/com/otclub/humate/mission/fragment/ReviewFragment.kt
  app/src/main/java/com/otclub/humate/mission/viewModel/MissionViewModel.kt
  app/src/main/res/layout/matching_fragment.xml
  app/src/main/res/layout/matching_item.xml
  app/src/main/res/layout/mission_cleared_details_fragment.xml
  app/src/main/res/layout/mission_cleared_fragment.xml
  app/src/main/res/layout/mission_cleared_item.xml
  app/src/main/res/layout/mission_image_pager.xml
  app/src/main/res/layout/mission_new_details_fragment.xml
  app/src/main/res/layout/mission_new_fragment.xml
  app/src/main/res/layout/mission_new_item.xml
  app/src/main/res/layout/mission_toolbar.xml
  app/src/main/res/layout/mission_upload_fragment.xml
  app/src/main/res/layout/mission_upload_image_item.xml
  app/src/main/res/layout/review_fragment.xml
  app/src/main/res/navigation/nav_graph.xml
Labels: documentation

#118 [MATE] 코드 주석 작성
  app/src/main/java/com/otclub/humate/CommonSplashActivity.kt
  app/src/main/java/com/otclub/humate/mate/adapter/PostDetailAdapter.kt
  app/src/main/java/com/otclub/humate/mate/adapter/PostListAdapter.kt
  app/src/main/java/com/otclub/humate/mate/api/PostService.kt
  app/src/main/java/com/otclub/humate/mate/data/LocalizedBranch.kt
  app/src/main/java/com/otclub/humate/mate/data/LocalizedTag.kt
  app/src/main/java/com/otclub/humate/mate/data/MateDetailResponseDTO.kt
  app/src/main/java/com/otclub/humate/mate/data/PostDetailResponseDTO.kt
  app/src/main/java/com/otclub/humate/mate/data/PostListFilterDTO.kt
  app/src/main/java/com/otclub/humate/mate/data/PostListResponseDTO.kt
  app/src/main/java/com/otclub/humate/mate/data/PostPlaceDetailResponseDTO.kt
  app/src/main/java/com/otclub/humate/mate/data/PostTagDetailResponseDTO.kt
  app/src/main/java/com/otclub/humate/mate/data/PostWriteOptionDTO.kt
  app/src/main/java/com/otclub/humate/mate/data/PostWritePlaceRequestDTO.kt
  app/src/main/java/com/otclub/humate/mate/data/PostWriteRequestDTO.kt
  app/src/main/java/com/otclub/humate/mate/data/PostWriteTagRequestDTO.kt
  app/src/main/java/com/otclub/humate/mate/data/Tag.kt
  app/src/main/java/com/otclub/humate/mate/fragment/PostDetailFragment.kt
  app/src/main/java/com/otclub/humate/mate/fragment/PostListFilterFragment.kt
  app/src/main/java/com/otclub/humate/mate/fragment/PostListFragment.kt
  app/src/main/java/com/otclub/humate/mate/fragment/PostWriteFragment.kt
  app/src/main/java/com/otclub/humate/mate/fragment/PostWriteOptionFragment.kt
  app/src/main/java/com/otclub/humate/mate/viewmodel/PostDetailViewModel.kt
  app/src/main/java/com/otclub/humate/mate/viewmodel/PostViewModel.kt
  app/src/main/java/com/otclub/humate/mate/viewmodel/PostWriteViewModel.kt
  app/src/main/res/layout/common_splash.xml
  app/src/main/res/layout/mate_fragment_post_detail.xml
  app/src/main/res/layout/mate_fragment_post_list.xml
  app/src/main/res/layout/mate_fragment_post_list_filter.xml
  app/src/main/res/layout/mate_fragment_post_write.xml
  app/src/main/res/layout/mate_fragment_post_write_option.xml
  app/src/main/res/layout/mate_item_place.xml
  app/src/main/res/layout/mate_item_post.xml
  app/src/main/res/layout/mate_item_store.xml
  app/src/main/res/layout/mate_post_write_dialog.xml
  app/src/main/res/layout/mate_spinner_item.xml
Labels: documentation

#114 [CHAT] 채팅방 생성, 채팅 탭 첫 화면 오류 수정
  app/build.gradle
  app/src/main/java/com/otclub/humate/MainActivity.kt
  app/src/main/java/com/otclub/humate/chat/adapter/MessageAdapter.kt
  app/src/main/java/com/otclub/humate/chat/adapter/RoomAdapter.kt
  app/src/main/java/com/otclub/humate/chat/api/ChatMainService.kt
  app/src/main/java/com/otclub/humate/chat/api/ChatRoomService.kt
  app/src/main/java/com/otclub/humate/chat/api/ChatService.kt
  app/src/main/java/com/otclub/humate/chat/data/ChatCreateCompanionRequestDTO.kt
  app/src/main/java/com/otclub/humate/chat/data/ChatMessage.kt
  app/src/main/java/com/otclub/humate/chat/data/ChatMessageWebSocketResponseDTO.kt
  app/src/main/java/com/otclub/humate/chat/data/ChatRoomDetailDTO.kt
  app/src/main/java/com/otclub/humate/chat/data/ChatSendMessageRequestDTO.kt
  app/src/main/java/com/otclub/humate/chat/data/CompanionCreateRequestDTO.kt
  app/src/main/java/com/otclub/humate/chat/data/MateUpdateRequestDTO.kt
  app/src/main/java/com/otclub/humate/chat/data/Message.kt
  app/src/main/java/com/otclub/humate/chat/data/MessageRequestDTO.kt
  app/src/main/java/com/otclub/humate/chat/data/MessageType.kt
  app/src/main/java/com/otclub/humate/chat/data/MessageWebSocketResponseDTO.kt
  app/src/main/java/com/otclub/humate/chat/data/RoomCreateRequestDTO.kt
  app/src/main/java/com/otclub/humate/chat/data/RoomCreateResponseDTO.kt
  app/src/main/java/com/otclub/humate/chat/data/RoomDetailDTO.kt
  app/src/main/java/com/otclub/humate/chat/fragment/ChatFragment.kt
  app/src/main/java/com/otclub/humate/chat/fragment/ChatMainFragment.kt
  app/src/main/java/com/otclub/humate/chat/fragment/ChatWebSocketListener.kt
  app/src/main/java/com/otclub/humate/chat/viewModel/ChatViewModel.kt
  app/src/main/java/com/otclub/humate/mate/fragment/PostDetailFragment.kt
  app/src/main/java/com/otclub/humate/mate/fragment/PostListFilterFragment.kt
  app/src/main/java/com/otclub/humate/mate/fragment/PostListFragment.kt
  app/src/main/java/com/otclub/humate/mate/fragment/PostWriteFragment.kt
  app/src/main/java/com/otclub/humate/retrofit/RetrofitConnection.kt
  app/src/main/res/layout/chat_activity_notice.xml
  app/src/main/res/layout/chat_dialog_confirmed.xml
  app/src/main/res/layout/chat_dialog_mate.xml
  app/src/main/res/layout/chat_dialog_mate_cancel.xml
  app/src/main/res/layout/chat_fragment.xml
  app/src/main/res/layout/chat_main_fragment.xml
  app/src/main/res/layout/chat_main_item.xml
  app/src/main/res/layout/chat_mate_button_default.xml
  app/src/main/res/layout/chat_mate_button_pressed.xml
  app/src/main/res/layout/chat_message_notice.xml
  app/src/main/res/layout/chat_message_received.xml
  app/src/main/res/layout/chat_message_sent.xml
  app/src/main/res/layout/chat_toolbar.xml
  app/src/main/res/menu/bottom_nav.xml
  app/src/main/res/navigation/nav_graph.xml
  app/src/main/res/values-en/strings.xml
  app/src/main/res/values-ko/strings.xml
  app/src/main/res/values/strings.xml
Labels: bug, documentation, ✨ feat
